'use client';

import DarkModeToggle from '@/components/DarkModeToggle';

export default function About() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-blue-50 via-purple-50 to-pink-50 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900 transition-colors duration-300 py-12 px-4 sm:px-6 lg:px-8">
      <DarkModeToggle />
      
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="text-center mb-16">
          <h1 className="text-4xl font-extrabold text-gray-900 dark:text-white sm:text-5xl sm:tracking-tight lg:text-6xl">
            About The Project
          </h1>
          <p className="mt-5 max-w-xl mx-auto text-xl text-gray-500 dark:text-gray-300">
            Empowering runners with personalized training plans to achieve their goals.
          </p>
        </div>

        {/* Content Grid */}
        <div className="grid grid-cols-1 gap-12">
          
          {/* Project Info */}
          <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-xl overflow-hidden">
            <div className="p-8 sm:p-10">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
                The Mission
              </h2>
              <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                This Training Plan Generator was created to simplify the process of preparing for half and full marathons. 
                By using your recent race times, we calculate personalized training paces and build a schedule that adapts 
                to your current fitness level. Our goal is to make structured training accessible to everyone, 
                helping you run smarter and faster.
              </p>
            </div>
          </div>

          {/* Data Credits */}
          <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-xl overflow-hidden">
            <div className="p-8 sm:p-10">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">
                Data Source
              </h2>
              <p className="text-gray-600 dark:text-gray-300 leading-relaxed">
                The training plans generated by this application are based on data compiled in this{' '}
                <a 
                  href="https://docs.google.com/spreadsheets/d/1ML785ZykGlAhbVmiHwnqmodeHUvcvMod4ZqCzAd8f_w/edit?gid=0#gid=0"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-blue-600 hover:underline dark:text-blue-400 font-medium"
                >
                  public spreadsheet
                </a>
                . We believe in transparency and open data to help runners improve their performance.
              </p>
            </div>
          </div>

          {/* Author Info */}
          <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-xl overflow-hidden">
            <div className="md:flex">
              <div className="p-8 sm:p-10 w-full">
                <div className="uppercase tracking-wide text-sm text-blue-600 dark:text-blue-400 font-semibold mb-1">
                  About the Creator
                </div>
                <h2 className="text-3xl font-bold text-gray-900 dark:text-white mb-6">
                  Sanket Tambare
                </h2>
                
                <div className="prose dark:prose-invert max-w-none text-gray-600 dark:text-gray-300 leading-relaxed space-y-4">
                  <p>
                    I am a software developer specialized in full-stack development. Since college days, I find myself to be inclined towards technology, society, psychology, blogging, designing, video editing, digital well-being, in short towards a variety of issues, technologies, topics and interests.
                  </p>
                  <p>
                    This has culminated in all-round interest across podcasts, development, writing, reading and much more! Also, all this exploration has helped me to decide what I am good at, what I am not good at, what I like, what I don&apos;t like and most importantly what I wish to do in my career and what I don&apos;t want to do.
                  </p>
                  <p>
                    And, here&apos;s what I wish to do: critically engage in new developments across technology, better thou-self everyday, learn something about stuff happening around me, understand it and enjoy this meaningful and purposeful journey!
                  </p>
                  <p className="font-medium text-gray-900 dark:text-white mt-6">
                    Interested in any of above topics? Get in touch if you wish to engage!
                  </p>
                </div>

                <div className="mt-8">
                  <a 
                    href="https://linktr.ee/daredavil" 
                    target="_blank" 
                    rel="noopener noreferrer"
                    className="inline-flex items-center px-6 py-3 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 transition-colors duration-200"
                  >
                    Connect with Sanket
                  </a>
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </main>
  );
}
